"""initial_migration

Revision ID: 93128d81d7cf
Revises: 
Create Date: 2026-07-22 14:23:30.862800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93128d81d7cf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant',
    sa.Column('uid_resto', sa.String(), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('adress', sa.String(length=100), nullable=False),
    sa.Column('status_ouvert', sa.Boolean(), nullable=False),
    sa.Column('horaire_ouverture', sa.Time(), nullable=False),
    sa.Column('horaire_fermeture', sa.Time(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('uid_resto'),
    sa.UniqueConstraint('uid_resto')
    )
    op.create_table('commande',
    sa.Column('uid_commande', sa.String(), nullable=False),
    sa.Column('uid_resto', sa.String(), nullable=False),
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('mode_retrait', sa.String(length=200), nullable=False),
    sa.Column('prix_total', sa.Float(), nullable=False),
    sa.Column('nom_client', sa.String(length=100), nullable=False),
    sa.Column('prenom_client', sa.String(length=100), nullable=False),
    sa.Column('tel_client', sa.Integer(), nullable=False),
    sa.Column('mail_client', sa.String(length=100), nullable=False),
    sa.Column('date_de_creation', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uid_resto'], ['restaurant.uid_resto'], ),
    sa.PrimaryKeyConstraint('uid_commande')
    )
    op.create_table('produit',
    sa.Column('uid_produit', sa.String(), nullable=False),
    sa.Column('uid_resto', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('mode_retrait', sa.String(length=200), nullable=False),
    sa.Column('prix_total', sa.Float(), nullable=False),
    sa.Column('dispo', sa.Boolean(), nullable=False),
    sa.Column('ingredients', sa.ARRAY(sa.String(length=100)), nullable=False),
    sa.ForeignKeyConstraint(['uid_resto'], ['restaurant.uid_resto'], ),
    sa.PrimaryKeyConstraint('uid_produit')
    )
    op.create_table('user',
    sa.Column('uid_user', sa.String(), nullable=False),
    sa.Column('uid_resto', sa.String(), nullable=True),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('prenom', sa.String(length=200), nullable=False),
    sa.Column('hash_mdp', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('roles', sa.ARRAY(sa.String(length=100)), nullable=False),
    sa.ForeignKeyConstraint(['uid_resto'], ['restaurant.uid_resto'], ),
    sa.PrimaryKeyConstraint('uid_user')
    )
    op.create_table('ligne_commande',
    sa.Column('uid_commande', sa.String(), nullable=False),
    sa.Column('uid_produit', sa.String(), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['uid_commande'], ['commande.uid_commande'], ),
    sa.ForeignKeyConstraint(['uid_produit'], ['produit.uid_produit'], ),
    sa.PrimaryKeyConstraint('uid_commande', 'uid_produit')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ligne_commande')
    op.drop_table('user')
    op.drop_table('produit')
    op.drop_table('commande')
    op.drop_table('restaurant')
    # ### end Alembic commands ###
